name: redis
version: 0.0.3
id: 6684b3cd-7a3c-4a6a-a338-cc10727000d1
description: "[Experimental] Redis by Helm Broker. This is an example add-on. It is not recommended for production scenarios."
displayName: "[Experimental] Redis"

tags: database, cache, experimental
labels:
  experimental: "true"
providerDisplayName: bitnami
longDescription: "[Experimental] Redis by Helm Broker. This is an example add-on. It is not recommended for production scenarios. Redis is an advanced key-value cache and store."
documentationURL: https://github.com/bitnami/bitnami-docker-redis
supportURL: https://bitnami.com/support
imageURL: https://cdn.auth0.com/blog/logos/redis-icon-logo.png
bindable: true
